# Generated by Django 5.2.16 on 2026-07-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_options_alter_item_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
